config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'

  resources :games do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, except: [ :new, :create ]
  resources :users, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :start_date, :end_date, presence: true
  # start_date needs to be after current date
  # end_date needs to be after start_date
  validates :approved, inclusion: { in: [true, false] }
  # validation for approved is either true or false
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category, :description ],
    using: {
      tsearch: { prefix: true }
    }

  validates :name, presence: true
  validates :name, length: { minimum: 3 }

  validates :description, presence: true
  validates :description, length: { minimum: 10 }

  validates :category, presence: true, inclusion: { in: ["Video games", "Consoles", "Board games", "Peripherals"],
                                                    message: "%<value> is not a valid category" }
  # This only allows certain categories (the ones in the array)

  validates :location, presence: true

  validates :price_per_day, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1000 }
  # This means the price has to be between 0.00 and 1000.00 (there is also a precision parameter in the schema for this)

  validates :user_id, presence: true

  has_one_attached :photo
  # implement with Cloudinary
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :username, presence: true
  validates :username, length: { minimum: 2}
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy ]

  def index
    @bookings = Booking.all

  end

  def show
    @number_of_days = (@booking.end_date - @booking.start_date).to_i
  end

  def new;
  end

  def create
    @booking = Booking.new(booking_params)
    @game = Game.find(params[:game_id])
    @booking.game = @game
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to game_path(@game), alert: @booking.errors.full_messages
    end
  end

  def edit; end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :game_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_game, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      @games = Game.search_by_name_and_category(params[:query])
    else
      @games = Game.all
    end

    @markers = @games.geocoded.map do |game|
      {
        lat: game.latitude,
        lng: game.longitude,
        info_window: render_to_string(partial: "info_window", locals: { game: game }),
        image_url: helpers.asset_url("logo.png")
      }
    end
  end

  def show
    @booking = Booking.new
    @markers = [{
      lat: @game.latitude,
      lng: @game.longitude,
      info_window: render_to_string(partial: "info_window", locals: { game: @game }),
      image_url: helpers.asset_url("logo.png")
    }]
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :category, :description, :location, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def profile
    @my_games = current_user.games
    @my_bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_bookings_edit_form.html.erb
<div class="container">
  <div class="row justify-content-center" style="margin: 24px;">
    <h1 style = "text-align: center;">Edit Booking for <%= @booking.game.name %></h1>
    <div class="col-6">
      <%= simple_form_for [@game, @booking] do |f|%>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <div class="row justify-content-center">
          <%= f.submit class: 'btn-red' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<%= render 'bookings_edit_form' %>

app/views/bookings/index.html.erb
<%# <div class="bookings-card-category" style="background-color: #EA3E4E;" >
  <h1 style= "font-weight: bold; font-family: 'Righteous';"> Bookings </h1>
</div> %>

<div class="container bookings-container">

  <% if @bookings.any?{ |booking| (booking.user == current_user)} %>

    <h2 class = "bookings-padding-top"> Your bookings </h2>
        <table class = "content-table">
            <thead>
              <tr>
                <th> Game </th>
                <th> Owner  </th>
                <th> Start date </th>
                <th> End date </th>
                <th> Total price (£)</th>
              </tr>
            </thead>
            <tbody>
              <% @bookings.each do |booking| %>
              <% if booking.user == current_user %>
                <tr>
                  <th class = "color-red"> <%= link_to "#{booking.game.name}", booking_path(booking), style: "color: #EA3E4E;" %> </th>
                  <th> <%= booking.game.user.username %> </th>
                  <th> <%= booking.start_date %></th>
                  <th> <%= booking.end_date %></th>
                  <th> £<%= number_with_precision((booking.end_date - booking.start_date).to_i * booking.game.price_per_day, precision: 2)%></th>
                </tr>
              <% end %>
              <% end %>
            </tbody>
        </table>
  <% else %>
    <h2 class = "bookings-padding-top"> Your bookings </h2>
    <div class="card mb-3" style="max-width: 800px; height: 200px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="https://blog.rentacenter.com/wp-content/uploads/2019/04/two-guys-happy-playing-video-games.jpg" class="img-fluid rounded-start booking-card-height" alt="...">
       </div>
      <div class="col-md-8 center-card-text booking-card-text">
        <div class="card-body booking-align-right">
          <h5 class="card-title" style = "color: #EA3E4E;"> You haven't booked any games!</h5>
          <p class="card-text"> Why not browse through the list of games we have to offer and try them out!</p>
          <div class = "bookings-btn-red" ><%= link_to "View games", games_path, class: "btn-red"%> </div>
       </div>
      </div>
     </div>
    </div>
  <% end %>

  <% @mybookings =  @bookings.select { |booking| (booking.game.user == current_user) } %>

  <% if @mybookings.any? %>

    <h2> Bookings on your games</h2>
    <table class = "content-table">
      <thead>
        <tr>
          <th> Game </th>
          <th> Renter </th>
          <th> Start date </th>
          <th> End date </th>
          <th> Total price (£)</th>
        </tr>
      </thead>
      <tbody>
        <% @mybookings.each do |booking|  %>
          <tr>
            <th class = "color-red"> <%= link_to "#{booking.game.name}", booking_path(booking), style: "color: #EA3E4E;"%> </th>
            <th> <%= booking.user.username %> </th>
            <th> <%= booking.start_date %></th>
            <th> <%= booking.end_date %></th>
            <th>£<%= number_with_precision((booking.end_date - booking.start_date).to_i * booking.game.price_per_day, precision: 2)%></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
   <h2> Bookings on your games </h2>
    <div class="card mb-3" style="max-width: 800px; height: 200px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2014/09/video-game-rental-options-featured.jpg" class="img-fluid rounded-start booking-card-height" alt="...">
       </div>
      <div class="col-md-8 center-card-text booking-card-text">
        <div class="card-body booking-align-right">
          <h5 class="card-title" style = "color: #EA3E4E;"> You don't have any bookings on your games ...</h5>
          <p class="card-text"> Why not list a new game and start making money today!</p>
          <div class = "bookings-btn-red"> <%= link_to "List games", new_game_path, class: "btn-red"%> </div>
       </div>
      </div>
     </div>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="booking-show-container">
  <h1>Booking Confirmation</h1>
  <div class="booking-info-container col-lg-6">
    <div class="booking-info-top">
      <div class="booking-image">
        <% if @booking.game.photo.attached? %>
          <%= cl_image_tag @booking.game.photo.key, height: 300, width: 300, crop: :pad %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1562229125-6d6075419a22?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974" style="object-fit: contain;">
        <% end %>
      </div>
      <div class="booking-text">
        <h5 class="booking-text-title"><%= @booking.game.name %></h5>
        <p><strong>Listed by</strong> <%= @booking.game.user.username %></p>
        <p><strong>Pick up location</strong> <%= @booking.game.location %></p>
        <p><strong>Start date</strong> <%= @booking.start_date %></p>
        <p><strong>End date</strong> <%= @booking.end_date %></p>
        <p><strong>Number of days</strong> <%= @number_of_days %> days</p>
        <p><strong>Total price</strong> £ <%= number_with_precision((@number_of_days * @booking.game.price_per_day), precision: 2) %></p>
      </div>
    </div>
    <div class="booking-navs-bottom">
      <%= link_to "Back to games", games_path, class: "btn btn-red" %>
      <div class="booking-user-navs">
        <%= link_to "My bookings", bookings_path, class: "booking-buttons-gray" %>
        <%= link_to "Edit booking", edit_booking_path(@booking, @booking.game), class: "booking-buttons-gray" %>
        <%= link_to "Delete booking", booking_path(@booking),
                                      method: :delete,
                                      data: { confirm: "Are you sure you want to delete the booking?" },
                                      class: "booking-buttons-gray" %>
      </div>
    </div>
  </div>
</div>




<!--
<div class="flex-container">
  <div class="container">

  <h1 style = "text-align: center;"> <%= @booking.game.name %></h1>

  <%= "Owner: #{@booking.game.user.username}" %> <br>
  <%= "Renter: #{@booking.user.username}" %> <br>
  <%= "Start date: #{@booking.start_date}"%> <br>
  <%= "End date: #{@booking.end_date}" %> <br>
  <% if user_signed_in? && current_user == @booking.game.user || @booking.user %>
       <button> <%= link_to "Delete", booking_path(@booking), method: :delete,
        data: { confirm: "Are you sure you want to delete #{@booking.game.name}?" } %> </button>
  <% end %> <br>
  <button> <%= link_to 'Back to bookings', bookings_path %> </button> <br>
  <button> <%= link_to 'View More games', games_path %> </button>

</div>

 <div class="container">
   <%= render 'bookings_edit_form' %>
  </div>
</div>
 -->

app/views/games/_booking_form.html.erb
 <div class="form-container">
    <%= simple_form_for [@game, @booking] do |f|%>
      <div class="dates text-left">
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
      </div>
      <div class="text-center">
        <%= f.submit "Request this game", class: 'btn-red' %>
      </div>
      <% end %>
</div>

app/views/games/_info_window.html.erb
<%= link_to game_path(game) do %>
  <div class="game-map-card">
    <% if game.photo.attached? %>
      <%= cl_image_tag game.photo.key, height: 300, width: 300, crop: :pad %>
    <% else %>
      <img src="https://images.unsplash.com/photo-1562229125-6d6075419a22?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974/300x300" />
    <% end %>
    <h3><%= game.name %></h3>
    <div class="game-map-card-details">
      <p class="category"><%= game.category %></p>
      <h6 class="card-price">£ <%= number_with_precision(game.price_per_day, precision: 2) %> per day </h6>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="container">
  <div class="row justify-content-center" style="margin: 24px;">
  <h1 style = "text-align: center;"> <%=  @game.name %></h1>
    <div class="col-6">
     <%= simple_form_for(@game) do |f|%>
        <%= f.input :name %>
        <%= f.input :category, :collection => ["Video games", "Consoles", "Board games", "Peripherals"] %>
        <%= f.input :location %>
        <%= f.input :price_per_day %>
        <%= f.input :description %>
        <div class="row justify-content-center">
          <%= f.submit class: 'btn-red' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="index-container">
  <div class="left-hand-games-result-wrap">
    <div class="title-elements">
      <h1>Available Games</h1>
      <%= link_to "List your game +", new_game_path, class: "btn-red" %>
    </div>
    <%= render 'shared/search', class: "games-search-bar"%>
    <% @games.each do |game| %>
    <div class="games-card-container">
      <%= link_to game_path(game) do %>
        <div class="card-game">
          <% if game.photo.attached? %>
            <%= cl_image_tag game.photo.key, height: 300, width: 300, crop: :pad %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1562229125-6d6075419a22?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974/300x300" />
          <% end %>
          <div class="card-content">
            <div class="card-text">
              <h2><%= game.name %></h2>
              <p><%= game.description %></p>
            </div>
            <div class="card-info">
              <p class="category"><%= game.category %></p>
              <h6 class="card-price">£ <%= number_with_precision(game.price_per_day, precision: 2) %> per day </h6>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <div id="map"
       style="height: 100vh;"
       data-controller="mapbox"
       data-mapbox-markers-value="<%= @markers.to_json %>"
       data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <div class="row justify-content-center" style="margin: 24px;">
  <h1 style = "text-align: center;">List New Game</h1>
    <div class="col-6">
      <%= simple_form_for (@game) do |f|%>
        <%= f.input :name %>
        <%= f.input :category, :collection => ["Video games", "Consoles", "Board games", "Peripherals"] %>
        <%= f.input :location,
                      input_html: { data: { geocoder_target: "location" } },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } }  %>
        <%= f.input :price_per_day, placeholder: 'GBP'%>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <div class="row justify-content-center">
          <%= f.submit class: 'btn-red' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="game-container">
    <div class="game-title-box">
      <h1><%= @game.name %></h1>
      <div class="title-navs">
        <p><%= @game.category %></p>
        <% if @game.user == current_user %>
          <%= link_to "Edit game", edit_game_path(@game), class: "title-buttons" %>
          <%= link_to "Delete game",
                      game_path(@game),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete #{@game.name}?" },
                      class: "title-buttons" %>
          <%= link_to "Back to games", games_path, class: "title-buttons" %>
        <% else %>
          <%= link_to "Back to games", games_path, class: "title-buttons" %>
        <% end %>
      </div>
    </div>

    <div class="game-info-boxes row">
      <div class="game-info-left col-lg-8">
        <% if @game.photo.attached? %>
          <%= cl_image_tag @game.photo.key, height: 400, width: 400, crop: :pad %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1562229125-6d6075419a22?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974" style="object-fit: contain;">
        <% end %>
        <div class="game-text">
          <h5><%= @game.description %></h5>
          <p><strong>Listed by</strong> <%= @game.user.username %></p>
          <p><strong>Pick-up location</strong> <%= @game.location %></p>
          <h6>£ <%= number_with_precision(@game.price_per_day, precision: 2) %> per day</h6>
        </div>
      </div>

      <div class="game-info-right col">
        <%= render "booking_form", game: @game, class: "game-booking-form" %>
        <div class="game-map"
             style="height: 50vh;"
             data-controller="mapbox"
             data-mapbox-markers-value="<%= @markers.to_json %>"
             data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Level-Up</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">
      <div class="page-container">
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
        <article class="flex-grow-1">
          <div class="main-content">
            <%= yield %>
          </div>
        </article>
        <%= render 'shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <%= image_tag "banner_illustration.png", id: "banner-image" %>
  <div class="banner-text">
    <div class="text-title">
      <h2>Welcome to</h2>
      <h1>Level-Up</h1>
    </div>
    <p>Share the fun near you and level-up your play!</p>
    <%= link_to "Let's-a go!", games_path, class: "btn-red" %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container profile-container">

  <div class="profile-page">
    <div class="profile-info">
      <div class="profile-details">
        <%= image_tag "user_avatar.png", :class => "profile-image" %>
          <div class="profile-text">
            <h3><%= (current_user.first_name).capitalize %> <%= (current_user.last_name).capitalize %></h3>
            <p><strong>Username</strong> <%= current_user.username %></p>
            <p><strong>Email</strong> <%= current_user.email %></p>
          </div>
      </div>
      <%= link_to 'Edit Info', 'users/edit', class: 'btn-red' %>
    </div>

    <div class="profile-games-listings">
      <div class="games-header">
        <h3>Active Listings</h3>
        <%= link_to 'List game', new_game_path, class: 'btn-red' %>
      </div>

      <% @my_games.each do |game| %>
        <div class="game-listing">
          <div class="game-image">
            <% if game.photo.attached? %>
            <%= cl_image_tag game.photo.key, height: 100, width: 100, crop: :pad %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1562229125-6d6075419a22?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974" style="height: 100px; width: 100px; object-fit: contain;">
          <% end %>
          </div>
          <div class="game-listing-text">
            <h5><%= game.name %></h5>
            <p><strong>Posted on</strong> <%= game.created_at.strftime("%F") %></p>
            <%= link_to 'More', game_path(game), class: 'more-info' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Share the <i class="fas fa-heart"></i> with Level-Up
    <%= link_to root_path do %>
      <%= image_tag "logo.png", :class => "footer-logo" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="flex-logo">
      <%= image_tag "logo.png" %>
      <h3 class="logo-text">Level-Up</h3>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li>
          <%= link_to root_path, class: "nav-link" do %>
            <i class="fa-brands fa-fort-awesome"></i>
            <p>Home</p>
          <% end %>
        </li>
        <li>
          <%= link_to games_path, class: "nav-link" do %>
          <i class="fa-solid fa-ghost"></i>
          <p>Games</p>
          <% end %>
        </li>
        <li>
          <%= link_to new_game_path, class: "nav-link" do %>
            <i class="fa-solid fa-puzzle-piece"></i>
            <p>List Game</p>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user_avatar.png", class: "avatar dropdown-toggle",
                                            id: "navbarDropdown",
                                            data: { bs_toggle: "dropdown" },
                                            'aria-haspopup': true,
                                            'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li>
          <%= link_to new_game_path, class: "nav-link" do %>
            <i class="fa-solid fa-puzzle-piece"></i>
            <p>List Game</p>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fa-solid fa-circle-user"></i>
            <p>Log in</p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_tag games_path, method: :get do %>
    <div class="search-component mb-4">
      <div class= "input-width">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a game"
        %>
      </div>
      <div>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>